# Codemagic config for unsigned IPA builds
workflows:
  ios-release:
    name: Clauntty iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        ZIG_VERSION: "0.15.2"
        XCODE_SCHEME: "Clauntty"
        XCODE_PROJECT: "Clauntty.xcodeproj"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          brew install gettext pkg-config
      - name: Clone and build Ghostty
        script: |
          # Install Zig
          curl -L "https://ziglang.org/download/$ZIG_VERSION/zig-macos-aarch64-$ZIG_VERSION.tar.xz" -o zig.tar.xz
          mkdir -p zig-bin
          tar -xJf zig.tar.xz -C zig-bin --strip-components=1
          export PATH="$PWD/zig-bin:$PATH"

          # Clone deps
          git clone https://github.com/eriklangille/rtach.git
          git clone -b clauntty https://github.com/eriklangille/ghostty.git
          git clone https://github.com/mitchellh/libxev.git

          # Build Ghostty
          cd ghostty
          zig build -Demit-xcframework -Doptimize=ReleaseFast -Demit-macos-app=false
          cd ..
      - name: Setup Frameworks
        script: |
          rm -rf Frameworks/GhosttyKit.xcframework
          mkdir -p Frameworks
          cp -R ghostty/macos/GhosttyKit.xcframework Frameworks/
      - name: Build unsigned IPA
        script: |
          mkdir -p build
          xcodebuild -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath "$PWD/build/Clauntty.xcarchive" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive

          # Package IPA
          mkdir -p Payload
          cp -r "build/Clauntty.xcarchive/Products/Applications/Clauntty.app" Payload/
          zip -r Clauntty.ipa Payload
    artifacts:
      - Clauntty.ipa
    publishing:
      email:
        recipients:
          - bobbytatum12@gmail.com
        attach_build: true
