workflows:
  ios-build:
    name: iOS Build with Ghostty
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          set -e
          
          # Capture the clone directory (current directory)
          SOURCE_DIR=$(pwd)
          # Use HOME directory for writable space
          BUILD_DIR="$HOME/clauntty-build"
          
          echo "=== Step 1: Setup directory structure ==="
          echo "SOURCE_DIR: $SOURCE_DIR"
          echo "BUILD_DIR: $BUILD_DIR"
          
          # Clean and recreate build directory
          rm -rf "$BUILD_DIR"
          mkdir -p "$BUILD_DIR"
          
          cd "$BUILD_DIR"
          
          echo "=== Step 2: Clone dependencies ==="
          git clone https://github.com/eriklangille/rtach.git
          git clone -b clauntty https://github.com/eriklangille/ghostty.git
          git clone https://github.com/eriklangille/libxev.git
          
          echo "=== Directory contents ==="
          ls -la
          
          echo ""
          echo "=== Step 3: Copy clauntty repo ==="
          # Copy the current repo to build directory
          cp -R "$SOURCE_DIR" "$BUILD_DIR/clauntty"
          ls -la "$BUILD_DIR/clauntty"
          
          echo ""
          echo "=== Step 4: Install Zig ==="
          brew install zig 2>/dev/null || true
          
          echo ""
          echo "=== Step 5: Build rtach ==="
          cd "$BUILD_DIR/rtach"
          # Patch zlib hash and force local libxev path
          python3 -c "
          import re
          content = open('build.zig.zon').read()
          content = content.replace('zlib-1.3.1-ZZQ7lc8NAABUbHzDe_cSWboCqMbrLkVwvFkKnojgeiT2', 'zlib-1.3.1-1-ZZQ7ldENAAA7qJjUXP6E6xnRuV-jDL9dyoJFc_eb3zQ6')
          content = re.sub(r'\.libxev\s*=\s*\.\{.*?\},', '.libxev = .{ .path = \"../libxev\" },', content, flags=re.DOTALL)
          open('build.zig.zon', 'w').write(content)
          "
          zig build cross
          
          echo ""
          echo "=== Step 6: Build Ghostty framework ==="
          cd "$BUILD_DIR/ghostty"
          # Force local libxev path
          python3 -c "
          import re
          content = open('build.zig.zon').read()
          content = re.sub(r'\.libxev\s*=\s*\.\{.*?\},', '.libxev = .{ .path = \"../libxev\" },', content, flags=re.DOTALL)
          open('build.zig.zon', 'w').write(content)
          "
          zig build -Demit-xcframework -Doptimize=ReleaseFast -Demit-macos-app=false
          
          echo "=== Ghostty output ==="
          ls -la "$BUILD_DIR/ghostty/zig-out/" || ls -la "$BUILD_DIR/ghostty/macos/"
          
          echo ""
          echo "=== Step 7: Setup Frameworks ==="
          cd "$BUILD_DIR/clauntty"
          rm -rf Frameworks/GhosttyKit.xcframework
          mkdir -p Frameworks
          cp -R "$BUILD_DIR/ghostty/macos/GhosttyKit.xcframework" Frameworks/
          ls -la Frameworks/
          
          echo ""
          echo "=== Step 8: Copy rtach binaries ==="
          if [ -d "$BUILD_DIR/rtach/zig-out/bin" ]; then
            mkdir -p Clauntty/Resources/rtach
            cp "$BUILD_DIR/rtach/zig-out/bin"/* Clauntty/Resources/rtach/ 2>/dev/null || true
            echo "rtach binaries copied"
          fi
          
          echo ""
          echo "=== Step 9: Build IPA ==="
          cd "$BUILD_DIR/clauntty"
          xcodebuild -project Clauntty.xcodeproj \
            -scheme Clauntty \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive
          
          echo ""
          echo "=== Step 10: Package IPA ==="
          mkdir -p build/Payload
          cp -r build/App.xcarchive/Products/Applications/Clauntty.app build/Payload/
          cd build && zip -r Clauntty.ipa Payload
          
          # Copy back to CM_CLONE_DIR for artifact pickup
          mkdir -p "$CM_CLONE_DIR/build"
          cp Clauntty.ipa "$CM_CLONE_DIR/build/"
          
          echo ""
          echo "✅ Build complete!"
          ls -la "$CM_CLONE_DIR/build/Clauntty.ipa"

    artifacts:
      - build/*.ipa
    
    publishing:
      email:
        recipients:
          - bobbytatum12@gmail.com
