workflows:
  ios-build:
    name: iOS Build with Ghostty
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          set -e
          
          # Capture the clone directory (current directory)
          SOURCE_DIR=$(pwd)
          # Use HOME directory for writable space
          BUILD_DIR="$HOME/clauntty-build"
          
          echo "=== Step 0: Xcode Environment Setup ==="
          xcodebuild -version
          xcode-select -p
          ls -d /Applications/Xcode*
          
          # Accept license and run first launch (sometimes helps with component registration)
          sudo xcodebuild -license accept || true
          sudo xcodebuild -runFirstLaunch || true
          
          echo "Checking metal availability..."
          xcrun -find metal || echo "metal not found via xcrun"
          xcrun -sdk iphoneos -find metal || echo "metal not found for iphoneos via xcrun"
          
          # Explicitly download the Metal toolchain if missing
          # We use -downloadComponent instead of just waiting for lazy load
          echo "Attempting to download Metal Toolchain..."
          xcodebuild -downloadComponent MetalToolchain || echo "Warning: Metal toolchain download command failed."
          
          # Final check
          xcrun -sdk iphoneos -find metal || echo "STILL missing metal for iphoneos"
          
          echo "=== Step 1: Setup directory structure ==="
          echo "SOURCE_DIR: $SOURCE_DIR"
          echo "BUILD_DIR: $BUILD_DIR"
          
          # Clean and recreate build directory
          rm -rf "$BUILD_DIR"
          mkdir -p "$BUILD_DIR"
          
          cd "$BUILD_DIR"
          
          echo "=== Step 2: Clone dependencies ==="
          git clone https://github.com/eriklangille/rtach.git
          git clone -b clauntty https://github.com/eriklangille/ghostty.git
          git clone https://github.com/eriklangille/libxev.git
          
          echo "=== Directory contents ==="
          ls -la
          
          echo ""
          echo "=== Step 3: Copy clauntty repo ==="
          # Copy the current repo to build directory
          cp -R "$SOURCE_DIR" "$BUILD_DIR/clauntty"
          ls -la "$BUILD_DIR/clauntty"
          
          echo ""
          echo "=== Step 4: Install Zig ==="
          # Install Zig 0.15.2-dev (master) or specific version
          # Since brew might not have 0.15.2 yet, we download it directly
          curl -L https://ziglang.org/builds/zig-macos-aarch64-0.15.0-dev.22+0d138c263.tar.xz -o zig.tar.xz || \
          curl -L https://ziglang.org/download/0.13.0/zig-macos-aarch64-0.13.0.tar.xz -o zig.tar.xz
          mkdir -p zig-dist && tar -xf zig.tar.xz -C zig-dist --strip-components 1
          export PATH="$(pwd)/zig-dist:$PATH"
          zig version
          
          echo ""
          echo "=== Step 5: Build rtach ==="
          cd "$BUILD_DIR/rtach"
          # Ensure zlib hash is correct
          zig fetch https://github.com/allyourcodebase/zlib/archive/refs/heads/main.tar.gz || true
          zig build cross
          
          echo ""
          echo "=== Step 6: Build Ghostty framework ==="
          cd "$BUILD_DIR/ghostty"
          # Force local libxev path
          python3 -c "
          import re
          content = open('build.zig.zon').read()
          content = re.sub(r'\.libxev\s*=\s*\.\{.*?\},', '.libxev = .{ .path = \"../libxev\" },', content, flags=re.DOTALL)
          open('build.zig.zon', 'w').write(content)
          "
          zig build -Demit-xcframework -Doptimize=ReleaseFast -Demit-macos-app=false
          
          echo "=== Ghostty output ==="
          ls -la "$BUILD_DIR/ghostty/zig-out/" || ls -la "$BUILD_DIR/ghostty/macos/"
          
          echo ""
          echo "=== Step 7: Setup Frameworks ==="
          cd "$BUILD_DIR/clauntty"
          rm -rf Frameworks/GhosttyKit.xcframework
          mkdir -p Frameworks
          cp -R "$BUILD_DIR/ghostty/macos/GhosttyKit.xcframework" Frameworks/
          ls -la Frameworks/
          
          echo ""
          echo "=== Step 8: Copy rtach binaries ==="
          if [ -d "$BUILD_DIR/rtach/zig-out/bin" ]; then
            mkdir -p Clauntty/Resources/rtach
            cp "$BUILD_DIR/rtach/zig-out/bin"/* Clauntty/Resources/rtach/ 2>/dev/null || true
            echo "rtach binaries copied"
          fi
          
          echo ""
          echo "=== Step 9: Build IPA ==="
          cd "$BUILD_DIR/clauntty"
          
          # Project file adjustments from user advice
          sed -i "" "s/65533RB4LC/${DEVELOPER_ID:-65533RB4LC}/g" Clauntty.xcodeproj/project.pbxproj
          sed -i "" "s/com.octerm.clauntty/${BUNDLE_ID:-com.octerm.clauntty}/g" Clauntty.xcodeproj/project.pbxproj

          xcodebuild -project Clauntty.xcodeproj \
            -scheme Clauntty \
            -sdk iphoneos \
            -configuration Release \
            -destination 'generic/platform=iOS,name=Any iOS Device' \
            -archivePath build/App.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            clean archive
          
          echo ""
          echo "=== Step 10: Package IPA ==="
          mkdir -p build/Payload
          if [ -d "build/App.xcarchive/Products/Applications/Clauntty.app" ]; then
            cp -r build/App.xcarchive/Products/Applications/Clauntty.app build/Payload/
            cd build && zip -r Clauntty.ipa Payload
          else
            echo "ERROR: Clauntty.app not found in archive"
            ls -R build/App.xcarchive
            exit 1
          fi
          
          # Copy back to SOURCE_DIR for artifact pickup
          mkdir -p "$SOURCE_DIR/build"
          cp build/Clauntty.ipa "$SOURCE_DIR/build/"
          
          echo ""
          echo "✅ Build complete!"
          ls -la "$SOURCE_DIR/build/Clauntty.ipa"

    artifacts:
      - build/*.ipa
    
    publishing:
      email:
        recipients:
          - bobbytatum12@gmail.com
